### ISSUE TITLE
Add wCELO balances in /treasury page

### ISSUE THREAD

**Issue by mintcloud** [0xProject/website#429]
The 0x Treasury will soon have wCELO balances as a result of the injection of capital by CELO foundation.

Currently, ZRX Portal [Treasury page](https://0x.org/zrx/treasury) does not support any other tokens than ZRX and MATIC.

The parts of the code that are likely to be modified are

- https://github.com/0xProject/website/blob/development/ts/pages/governance/treasury_breakdown.tsx#L201 (for fetching CELO prices, coingecko URL should be https://api.coingecko.com/api/v3/simple/price?ids=celo&vs_currencies=usd)
- https://github.com/0xProject/website/blob/development/ts/pages/governance/treasury_breakdown.tsx#L196 (Treasury page)
- https://github.com/0xProject/website/blob/development/ts/components/governance/hero.tsx#L218 (hero functions to update balances)

The Treasury has already 1 wCELO balance so it could be tested even before the entire funds are transferred.

**Comment by Ajmasta** [comment]
Hello,

Would love to work on this. I actually have a pretty straightforward idea on how to automatize all of this so that anytime you have a token you don't have to change the code (except perhaps to change the color associated with a specific token in a pie chart). But I am running into a lot of issues to simply install and build this repo. 

From what I gathered, this repo uses an old version of node-sass (4.3) which has a dependency on an old version of node-gyp (3.8). These two packages are only compatible with Python 2, which has been EOL for more than a year, and they fail when using python 3 due to a print statement (similar to [here](https://github.com/nodejs/node-gyp/issues/1977)). This issue has been fixed in the latest versions of node-sass and node-gyp. 

I tried to upgrade these two dependencies, but I've been unsuccesful as I run into a " ENOENT: no such file or directory, lstat " error, which seems to be related to a badly formatted path but not sure. 

Anyway, I am using windows, is that why I am running into all these issues? Am I missing something obvious?

**Comment by vjnrv** [comment]
> Hello,
> 
> Would love to work on this. I actually have a pretty straightforward idea on how to automatize all of this so that anytime you have a token you don't have to change the code (except perhaps to change the color associated with a specific token in a pie chart). But I am running into a lot of issues to simply install and build this repo.
> 
> From what I gathered, this repo uses an old version of node-sass (4.3) which has a dependency on an old version of node-gyp (3.8). These two packages are only compatible with Python 2, which has been EOL for more than a year, and they fail when using python 3 due to a print statement (similar to [here](https://github.com/nodejs/node-gyp/issues/1977)). This issue has been fixed in the latest versions of node-sass and node-gyp.
> 
> I tried to upgrade these two dependencies, but I've been unsuccesful as I run into a " ENOENT: no such file or directory, lstat " error, which seems to be related to a badly formatted path but not sure.
> 
> Anyway, I am using windows, is that why I am running into all these issues? Am I missing something obvious?

I had no problems building this repo, i have python 2 and 3 installed. You can't install Python 2? It runs standalone of version 3.

**Comment by Ajmasta** [comment]
> 

Hey,thanks for the reply. I do have python 2 installed, but the dependencies should still be updated. These modules are several major versions behind.

**Comment by birimbau** [comment]
@Ajmasta had a similar issue, removing the yarn.lock file and node_modules folder and performing a yarn install after worked for me.

**Comment by vjnrv** [comment]
Thank you @birimbau, let's hope this works for @Ajmasta.

**Comment by Ajmasta** [comment]
> @Ajmasta had a similar issue, removing the yarn.lock file and node_modules folder and performing a yarn install after worked for me.

Thanks a lot to you both! That did the trick :)
