### ISSUE TITLE
Invalid signature error when signing order using Parity Signer Chrome Extension

### ISSUE THREAD

**Issue by fabioberger** [0xProject/website#53]
When attempting to sign an order using Parity Signer, the signing fails.

Tested on Kovan.

**Comment by LogvinovLeon** [comment]
Parity uses rsv instead of vrs

**Comment by willwarren89** [comment]
It's not clear if Parity adds the `Ethereum Signed Message` header yet or not.

**Comment by yuanfeiz** [comment]
So even if the transaction is mined successfully in the network, there's still chances to fail generating the order?

**Comment by willwarren89** [comment]
@yuanfeiz no, this should never be the case. The [transaction](https://kovan.etherscan.io/tx/0x317fc1305420404663e1f420c3b0d9aac327395e0ab913e60be8c1e7ad029c44) you've referenced appears to be setting an Allowance for an ERC20 token and not interacting with 0x's system of smart contracts.

**Comment by yuanfeiz** [comment]
Yup, I was wrong. Thanks for pointing out, looking forward to seeing this issue fixed. 👍

**Comment by fabioberger** [comment]
Parity Signers' web3 instance does not support async calls so part of the fix will be to default to sync methods if the async call fails. Found a ship-blocking bug on their end and have filed an issue: https://github.com/paritytech/parity-ui/issues/117. Once this gets resolves, we should be able to support Parity Signer.

**Comment by tomusdrw** [comment]
Parity does prepend `\x19Ethereum Signed Message:\n{len(message)}` before signing. Signature order has also been changed in 1.6.7 and upcoming 1.7.x, it will return `rsv` (same as geth; where `v is [27, 28]`).

Synchronous calls are not supported by design, a good explanation given here: https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client

**Comment by fabioberger** [comment]
@yuanfeiz OTC is now compatible with Parity Signer: #68
